// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp1WOw3sA1JTSsC7_tVPK7QG_B3XIwwFM',
    appId: '1:477137598697:web:8b215aafd52dcb2ae89878',
    messagingSenderId: '477137598697',
    projectId: 'hersphere-e2d6e',
    authDomain: 'hersphere-e2d6e.firebaseapp.com',
    storageBucket: 'hersphere-e2d6e.appspot.com',
    measurementId: 'G-ZKHY3RXZ8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmnZODzfTy_A2fgE6wZJfhf1xyJVhCDQU',
    appId: '1:477137598697:android:db9239dfb41900d3e89878',
    messagingSenderId: '477137598697',
    projectId: 'hersphere-e2d6e',
    storageBucket: 'hersphere-e2d6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq6gsAPHqqFeHrynI8QqQo-SKsV5TbfvY',
    appId: '1:477137598697:ios:78418d896d2459b8e89878',
    messagingSenderId: '477137598697',
    projectId: 'hersphere-e2d6e',
    storageBucket: 'hersphere-e2d6e.appspot.com',
    iosClientId: '477137598697-9q9ii4aan9s7ff5jph7jq90a5ogemhif.apps.googleusercontent.com',
    iosBundleId: 'com.example.herSphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq6gsAPHqqFeHrynI8QqQo-SKsV5TbfvY',
    appId: '1:477137598697:ios:78418d896d2459b8e89878',
    messagingSenderId: '477137598697',
    projectId: 'hersphere-e2d6e',
    storageBucket: 'hersphere-e2d6e.appspot.com',
    iosClientId: '477137598697-9q9ii4aan9s7ff5jph7jq90a5ogemhif.apps.googleusercontent.com',
    iosBundleId: 'com.example.herSphere',
  );
}
